// SPDX-License-Identifier: UNLICENSED
// !! THIS FILE WAS AUTOGENERATED BY abi-to-sol v0.6.4. SEE SOURCE BELOW. !!
pragma solidity >=0.7.0 <0.9.0;

interface ITokemakRewardHash {
    event CycleHashAdded(
        uint256 cycleIndex,
        string latestClaimableHash,
        string cycleHash
    );
    event OwnershipTransferred(
        address indexed previousOwner,
        address indexed newOwner
    );

    function cycleHashes(uint256)
        external
        view
        returns (string memory latestClaimable, string memory cycle);

    function latestCycleIndex() external view returns (uint256);

    function owner() external view returns (address);

    function renounceOwnership() external;

    function setCycleHashes(
        uint256 index,
        string memory latestClaimableIpfsHash,
        string memory cycleIpfsHash
    ) external;

    function transferOwnership(address newOwner) external;
}

// THIS FILE WAS AUTOGENERATED FROM THE FOLLOWING ABI JSON:
/*
[{"inputs":[],"stateMutability":"nonpayable","type":"constructor"},{"anonymous":false,"inputs":[{"indexed":false,"internalType":"uint256","name":"cycleIndex","type":"uint256"},{"indexed":false,"internalType":"string","name":"latestClaimableHash","type":"string"},{"indexed":false,"internalType":"string","name":"cycleHash","type":"string"}],"name":"CycleHashAdded","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"previousOwner","type":"address"},{"indexed":true,"internalType":"address","name":"newOwner","type":"address"}],"name":"OwnershipTransferred","type":"event"},{"inputs":[{"internalType":"uint256","name":"","type":"uint256"}],"name":"cycleHashes","outputs":[{"internalType":"string","name":"latestClaimable","type":"string"},{"internalType":"string","name":"cycle","type":"string"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"latestCycleIndex","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"owner","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"renounceOwnership","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint256","name":"index","type":"uint256"},{"internalType":"string","name":"latestClaimableIpfsHash","type":"string"},{"internalType":"string","name":"cycleIpfsHash","type":"string"}],"name":"setCycleHashes","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"newOwner","type":"address"}],"name":"transferOwnership","outputs":[],"stateMutability":"nonpayable","type":"function"}]
*/
